spring:
  application:
    name: MUSIC-HQ-END
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/music-hq?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 514179
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

jwt:
  secret: CZHQ
  expiration: 86400000
  token-name: music-hq-end-token
